### ISSUE TITLE
Replace `django-datetime-widget` with `django-bootstrap-datepicker-plus`

### ISSUE THREAD

**Issue by jag1g13** [softwaresaved/lowfat#616]
Current widget hasn't been updated in many years and doesn't work with Django 2.1 or later.
This is the cause of test failures in:

- `test_expense_review`
- `test_expense_review_relative`
- `test_fund`

and probably some of the others (haven't checked)

```
self = <django.forms.boundfield.BoundField object at 0x7f1b02d4fd50>
widget = <datetimewidget.widgets.DateWidget object at 0x7f1b02d89610>
attrs = {'id': 'id_asked_for_authorization_date'}, only_initial = False

    def as_widget(self, widget=None, attrs=None, only_initial=False):
        """
        Render the field by rendering the passed widget, adding any HTML
        attributes passed as attrs. If a widget isn't specified, use the
        field's default widget.
        """
        widget = widget or self.field.widget
        if self.field.localize:
            widget.is_localized = True
        attrs = attrs or {}
        attrs = self.build_widget_attrs(attrs, widget)
        if self.auto_id and 'id' not in widget.attrs:
            attrs.setdefault('id', self.html_initial_id if only_initial else self.auto_id)
        return widget.render(
            name=self.html_initial_name if only_initial else self.html_name,
            value=self.value(),
            attrs=attrs,
>           renderer=self.form.renderer,
        )
E       TypeError: render() got an unexpected keyword argument 'renderer'

.venv/lib64/python3.7/site-packages/django/forms/boundfield.py:93: TypeError
```

**Comment by jag1g13** [comment]
See https://github.com/monim67/django-bootstrap-datepicker-plus

**Comment by jag1g13** [comment]
Reason for choosing this replacement library is that we've used it in other projects, e.g. BRECcIA at https://github.com/Southampton-RSG/breccia-mapper/blob/40c138de006c3d93ddd97dcb9073ba394a72163d/people/forms.py#L180

**Comment by PipGrylls** [comment]
Widget added in commit commit 97efc9a429a25e3bb24822cf953be1c0153ec52e
